Update update_readme.yml

diff --git a/.github/workflows/update_readme.yml b/.github/workflows/update_readme.yml
--- a/.github/workflows/update_readme.yml
+++ b/.github/workflows/update_readme.yml
@@ -87,9 +87,9 @@ jobs:
           #fi
           
           if [[ -z "$FILE_SHA" ]]; then
-          #  echo "Failed to retrieve the current commit SHA for the file: $FILE_PATH"
-          #  exit 1
-          #fi
+            echo "Failed to retrieve the current FILE SHA for the file: $FILE_PATH"
+            exit 1
+          fi
           
           # Decode the file contents
           FILE_CONTENT=$(echo "$FILE_CONTENT" | base64 -d)
