Update update_readme.yml

diff --git a/.github/workflows/update_readme.yml b/.github/workflows/update_readme.yml
--- a/.github/workflows/update_readme.yml
+++ b/.github/workflows/update_readme.yml
@@ -81,10 +81,15 @@ jobs:
           #echo "CURRENT_COMMIT_SHA: $CURRENT_COMMIT_SHA"
           #echo "VECTOR_COMMIT_SHA: $VECTOR_COMMIT_SHA"
           
-          if [[ -z "$CURRENT_COMMIT_SHA" ]]; then
-            echo "Failed to retrieve the current commit SHA for the file: $FILE_PATH"
-            exit 1
-          fi
+          #if [[ -z "$CURRENT_COMMIT_SHA" ]]; then
+          #  echo "Failed to retrieve the current commit SHA for the file: $FILE_PATH"
+          #  exit 1
+          #fi
+          
+          if [[ -z "$FILE_SHA" ]]; then
+          #  echo "Failed to retrieve the current commit SHA for the file: $FILE_PATH"
+          #  exit 1
+          #fi
           
           # Decode the file contents
           FILE_CONTENT=$(echo "$FILE_CONTENT" | base64 -d)
