Update update_readme.yml

diff --git a/.github/workflows/update_readme.yml b/.github/workflows/update_readme.yml
--- a/.github/workflows/update_readme.yml
+++ b/.github/workflows/update_readme.yml
@@ -1,4 +1,4 @@
-name: Update README from pyfluxconserving
+name: Update README and meta.yaml from pyfluxconserving
 
 on:
   push:
@@ -129,5 +129,67 @@ jobs:
             -H "X-GitHub-Api-Version: 2022-11-28" \
             -d "$JSON_DATA" \
             "https://api.github.com/repos/neutrinomuon/pyfluxconserving/contents/$FILE_PATH")
+
+          echo "$RESPONSE"
+          
+      - name: Update meta.yaml with new version
+        run: |
+          TOKEN=${{ secrets.GITHUB_TOKEN }}
+          FILE_PATH="meta.yaml"
+          BRANCH="main"
+          COMMIT_MESSAGE="Update README with new version"
+          
+          # Get the file SHA from the /contents endpoint
+          # Needs to use FILES_SHA and not COMMIT_SHA for the update of the file
+          FILE_SHA=$(curl -s -X GET \
+            -H "Authorization: Bearer $TOKEN" \
+            -H "Accept: application/vnd.github+json" \
+            "https://api.github.com/repos/neutrinomuon/pyfluxconserving/contents/pyfluxconserving/$FILE_PATH?ref=$BRANCH" | jq -r '.sha')
+
+          # Get the current file contents
+          FILE_CONTENT=$(curl -s -X GET \
+            -H "Authorization: Bearer $TOKEN" \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/neutrinomuon/pyfluxconserving/contents/pyfluxconserving/$FILE_PATH?ref=$BRANCH" | jq -r '.content')
+
+          # Print COMMIT_SHAs
+          echo "FILE_SHA: $FILE_SHA"
+          
+          if [[ -z "$FILE_SHA" ]]; then
+            echo "Failed to retrieve the current FILE SHA for the file: $FILE_PATH"
+            exit 1
+          fi
+          
+          # Decode the file contents
+          FILE_CONTENT=$(echo "$FILE_CONTENT" | base64 -d)
+
+          # Update the file content with the new version
+          NEW_VERSION=$(cat version.txt)
+          #UPDATED_CONTENT=$(echo "$FILE_CONTENT" | sed "s/last stable version: .*/last stable version: $NEW_VERSION/")
+          #UPDATED_CONTENT=$(echo "$FILE_CONTENT" | sed "s/{% set version = \".*\" %}/{% set version = \"$NEW_VERSION\" %}/")
+          UPDATED_CONTENT=$(echo "$FILE_CONTENT" | sed "s/{% set version = \".*\" %}/{% set version = \"$NEW_VERSION\" %}/")
+
+          # Encode the updated content
+          # UPDATE_CONTENT_normal=$(echo -n "$UPDATED_CONTENT")
+          UPDATED_CONTENT=$(echo -n "$UPDATED_CONTENT" | base64)
+
+          # Print debug information
+          echo "TOKEN: $TOKEN"
+          echo "NEW_VERSION: $NEW_VERSION"
+          
+           # Prepare the JSON data
+          JSON_DATA=$(jq -n --arg message "$COMMIT_MESSAGE" --arg content "$UPDATED_CONTENT" --arg branch "$BRANCH" --arg sha $FILE_SHA \
+            '{message: $message, content: $content, branch: $branch, sha: $sha}')
+
+          # echo "JSON_DATA: $JSON_DATA"
+
+          # Update the file on GitHub
+          RESPONSE=$(curl -s -X PUT \
+            -H "Authorization: Bearer $TOKEN" \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -d "$JSON_DATA" \
+            "https://api.github.com/repos/neutrinomuon/pyfluxconserving/contents/pyfluxconserving/$FILE_PATH")
 
           echo "$RESPONSE"
